name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v6
      id: vcpkg
      with:
        pkgs: llvm opencv4
        triplet: x64-windows-release
        token: ${{ github.token }}
        github-binarycache: true
    - uses: actions/checkout@v4
    - name: build
      run: cargo build --verbose
    - name: run tests
      run: cargo test --verbose
